# Generated by Django 3.1 on 2020-11-26 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='estime',
            new_name='estimate',
        ),
    ]
